# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

SCHEME = "fastlane101"
APP_IDENTIFIER = "cs.com.fastlane.test"

platform :ios do
  # desc "Description of what the lane does"
  # lane :custom_lane do
  #   # add actions here: https://docs.fastlane.tools/actions
  # end

  lane :tests do
    run_tests(
      scheme: SCHEME,
      device: 'iPhone 8'
      )
  end

  lane :screenshots do
    capture_screenshots(
      devices: "iPhone 8",
      clear_previous_screenshots: true
    )
    frame_screenshots(
      white: true
    )
    # upload_to_app_store
  end

  lane :beta do
    # match(
    #   app_identifier: APP_IDENTIFIER,
    #   type: "development",
    # )
    build_app(scheme: SCHEME)
  end

  lane :testflight do
    match(
      app_identifier: APP_IDENTIFIER,
      type: "development",
    )
    build_app(scheme: SCHEME)
    upload_to_testflight
  end

end
